In [1]:
import pandas as pd

In [13]:
order_list = pd.read_excel(r"C:\Users\TEMP.CLOUDNINE\Documents\Nandini\Placement Assignments\Jar\List_of_Orders.xlsx")
order_details = pd.read_excel(r"C:\Users\TEMP.CLOUDNINE\Documents\Nandini\Placement Assignments\Jar\Order_Details.xlsx")
sales_target = pd.read_excel(r"C:\Users\TEMP.CLOUDNINE\Documents\Nandini\Placement Assignments\Jar\Sales_target.xlsx")

In [14]:
order_list.head()

  Order ID           Order Date CustomerName           State       City
0  B-25601  2018-01-04 00:00:00       Bharat         Gujarat  Ahmedabad
1  B-25602  2018-01-04 00:00:00        Pearl     Maharashtra       Pune
2  B-25603  2018-03-04 00:00:00        Jahan  Madhya Pradesh     Bhopal
3  B-25604  2018-03-04 00:00:00       Divsha       Rajasthan     Jaipur
4  B-25605  2018-05-04 00:00:00      Kasheen     West Bengal    Kolkata

In [7]:
orders_list.describe()

       Order ID  Order Date CustomerName           State    City
count       500         500          500             500     500
unique      500         307          332              19      24
top     B-25601  24-11-2018       Shreya  Madhya Pradesh  Indore
freq          1           7            6             101      76

In [8]:
order_details.head()

  Order ID  Amount  Profit  Quantity     Category      Sub-Category
0  B-25601    1275   -1148         7    Furniture         Bookcases
1  B-25601      66     -12         5     Clothing             Stole
2  B-25601       8      -2         3     Clothing       Hankerchief
3  B-25601      80     -56         4  Electronics  Electronic Games
4  B-25602     168    -111         2  Electronics            Phones

In [10]:
order_details.describe()

            Amount       Profit     Quantity
count  1500.000000  1500.000000  1500.000000
mean    287.668000    15.970000     3.743333
std     461.050488   169.140565     2.184942
min       4.000000 -1981.000000     1.000000
25%      45.000000    -9.250000     2.000000
50%     118.000000     9.000000     3.000000
75%     322.000000    38.000000     5.000000
max    5729.000000  1698.000000    14.000000

In [11]:
sales_target.head()

  Month of Order Date   Category  Target
0          2026-04-18  Furniture   10400
1          2026-05-18  Furniture   10500
2          2026-06-18  Furniture   10600
3          2026-07-18  Furniture   10800
4          2026-08-18  Furniture   10900

In [12]:
sales_target.describe()

       Month of Order Date        Target
count                   36     36.000000
mean   2026-07-03 18:00:00  12108.333333
min    2026-01-19 00:00:00   9000.000000
25%    2026-04-10 12:00:00  10050.000000
50%    2026-07-03 00:00:00  11450.000000
75%    2026-09-25 12:00:00  14500.000000
max    2026-12-18 00:00:00  16000.000000
std                    NaN   2667.837541

In [17]:
# Merge datasets using Order ID
merged = pd.merge(order_list, order_details, on='Order ID')

In [16]:
merged.head()

,Order ID,Order Date,CustomerName,State,City,Amount,Profit,Quantity,Category,Sub-Category
0,B-25601,2018-01-04 00:00:00,Bharat,Gujarat,Ahmedabad,1275,-1148,7,Furniture,Bookcases
1,B-25601,2018-01-04 00:00:00,Bharat,Gujarat,Ahmedabad,66,-12,5,Clothing,Stole
2,B-25601,2018-01-04 00:00:00,Bharat,Gujarat,Ahmedabad,8,-2,3,Clothing,Hankerchief
3,B-25601,2018-01-04 00:00:00,Bharat,Gujarat,Ahmedabad,80,-56,4,Electronics,Electronic Games
4,B-25602,2018-01-04 00:00:00,Pearl,Maharashtra,Pune,168,-111,2,Electronics,Phones

In [18]:
# Total Sales by Category
category_sales = merged.groupby('Category')['Amount'].sum()

In [19]:
category_sales

Category
Clothing       139054
Electronics    165267
Furniture      127181
Name: Amount, dtype: int64

In [24]:
# Average Profit per Order
avg_profit = merged.groupby('Category').agg(Average_Profit_Per_Order=("Profit", "mean"))

In [25]:
avg_profit

             Average_Profit_Per_Order
Category
Clothing                    11.762908
Electronics                 34.071429
Furniture                    9.456790

In [26]:
# Profit Margin
profit_stats = merged.groupby("Category").agg(Total_Sales=("Amount", "sum"),Total_Profit=("Profit", "sum"))

In [27]:
profit_stats

             Total_Sales  Total_Profit
Category
Clothing          139054         11163
Electronics       165267         10494
Furniture         127181          2298

In [28]:
profit_stats['Profit_Margin (%)'] = ( profit_stats['Total_Profit'] / profit_stats['Total_Sales']) * 100

In [29]:
profit_stats

             Total_Sales  Total_Profit  Profit_Margin (%)
Category
Clothing          139054         11163           8.027817
Electronics       165267         10494           6.349725
Furniture         127181          2298           1.806874

In [30]:
category_analysis = profit_stats.join(avg_profit)

In [32]:
category_analysis

,Total_Sales,Total_Profit,Profit_Margin (%),Average_Profit_Per_Order
Category,,,,
Clothing,139054,11163,8.027817,11.762908
Electronics,165267,10494,6.349725,34.071429
Furniture,127181,2298,1.806874,9.456790

In [33]:
best = category_analysis.sort_values(
    by=["Profit_Margin (%)", "Average_Profit_Per_Order"],
    ascending=False
)

# Worst Category
worst = category_analysis.sort_values(
    by=["Profit_Margin (%)", "Average_Profit_Per_Order"]
)

print("\nTop Performing Category")
print(best.head(1))

print("\nUnderperforming Category")
print(worst.head(1))

Top Performing Category
          Total_Sales  Total_Profit  Profit_Margin (%)  \
Category
Clothing       139054         11163           8.027817

          Average_Profit_Per_Order
Category
Clothing                 11.762908

Underperforming Category
           Total_Sales  Total_Profit  Profit_Margin (%)  \
Category
Furniture       127181          2298           1.806874

           Average_Profit_Per_Order
Category
Furniture                   9.45679

In [34]:

furniture = target[target["Category"] == "Furniture"].copy()

In [35]:
furniture

   Month of Order Date   Category  Target
0           2026-04-18  Furniture   10400
1           2026-05-18  Furniture   10500
2           2026-06-18  Furniture   10600
3           2026-07-18  Furniture   10800
4           2026-08-18  Furniture   10900
5           2026-09-18  Furniture   11000
6           2026-10-18  Furniture   11100
7           2026-11-18  Furniture   11300
8           2026-12-18  Furniture   11400
9           2026-01-19  Furniture   11500
10          2026-02-19  Furniture   11600
11          2026-03-19  Furniture   11800

In [41]:
furniture["Month"] = pd.to_datetime(furniture["Month of Order Date"]).dt.month

In [42]:
furniture

   Month of Order Date   Category  Target  Month
0           2026-04-18  Furniture   10400      4
1           2026-05-18  Furniture   10500      5
2           2026-06-18  Furniture   10600      6
3           2026-07-18  Furniture   10800      7
4           2026-08-18  Furniture   10900      8
5           2026-09-18  Furniture   11000      9
6           2026-10-18  Furniture   11100     10
7           2026-11-18  Furniture   11300     11
8           2026-12-18  Furniture   11400     12
9           2026-01-19  Furniture   11500      1
10          2026-02-19  Furniture   11600      2
11          2026-03-19  Furniture   11800      3

In [43]:
furniture = furniture.sort_values("Month")

# Month-over-Month Percentage Change
furniture["MoM_Target_Change (%)"] = (furniture["Target"].pct_change() * 100)

print(furniture)

   Month of Order Date   Category  Target  Month  MoM_Target_Change (%)
9           2026-01-19  Furniture   11500      1                    NaN
10          2026-02-19  Furniture   11600      2               0.869565
11          2026-03-19  Furniture   11800      3               1.724138
0           2026-04-18  Furniture   10400      4             -11.864407
1           2026-05-18  Furniture   10500      5               0.961538
2           2026-06-18  Furniture   10600      6               0.952381
3           2026-07-18  Furniture   10800      7               1.886792
4           2026-08-18  Furniture   10900      8               0.925926
5           2026-09-18  Furniture   11000      9               0.917431
6           2026-10-18  Furniture   11100     10               0.909091
7           2026-11-18  Furniture   11300     11               1.801802
8           2026-12-18  Furniture   11400     12               0.884956

In [44]:
threshold = 20

fluctuations = furniture[
    furniture["MoM_Target_Change (%)"].abs() > threshold
]

print("\nMonths with Significant Target Changes")
print(fluctuations)

Months with Significant Target Changes
Empty DataFrame
Columns: [Month of Order Date, Category, Target, Month, MoM_Target_Change (%)]
Index: []

In [45]:
top_states = (merged.groupby("State")["Order ID"].count().sort_values(ascending=False).head(5))

In [47]:
print("\nTop 5 States by Order Count")
print(top_states)

# Performance of Top States
state_analysis = (
    merged[merged["State"].isin(top_states.index)]
    .groupby("State")
    .agg(
        Order_Count=("Order ID", "count"),
        Total_Sales=("Amount", "sum"),
        Average_Profit=("Profit", "mean")
    )
    .sort_values(by="Order_Count", ascending=False)
)

print("\nState Performance")
print(state_analysis)

Top 5 States by Order Count
State
Madhya Pradesh    340
Maharashtra       290
Gujarat            87
Delhi              74
Rajasthan          74
Name: Order ID, dtype: int64

State Performance
                Order_Count  Total_Sales  Average_Profit
State
Madhya Pradesh          340       105140       16.326471
Maharashtra             290        95348       21.296552
Gujarat                  87        21058        5.344828
Delhi                    74        22531       40.364865
Rajasthan                74        21149       16.986486